services:
  gradio:
    container_name: gradio
    build:
      context: .
      dockerfile: gradio/Dockerfile.gradio
    ports:
      - "7860:7860"
    volumes:
      - ./gradio:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - HAYHOOKS_URL=http://hayhooks:1416
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - hayhooks
      - qdrant

  hayhooks:
    container_name: hayhooks
    build: .
    ports:
      - "1416:1416"
    expose:
      - 1416
    volumes:
      - ./pipelines:/code/pipelines
      - ./components:/code/components
      - ./cache:/code/cache
    environment:
      - PYTHONPATH=.
      - PYTHONDONTWRITEBYTECODE=1
      - OLLAMA_URL=http://host.docker.internal:11434
      - QDRANT_URL=http://qdrant:6333
      - TIKA_URL=http://tika:9998
      - HAYHOOKS_PIPELINES_DIR=/code/pipelines
      - FASTEMBED_CACHE_PATH=/code/cache/models/fastembed
      - NLTK_DATA=/code/cache/nltk_data
      - TIKTOKEN_CACHE_DIR=/code/cache/tiktoken
      - LOG=DEBUG
    depends_on:
      - tika
      - qdrant
    restart: unless-stopped

  tika:
    container_name: tika
    image: apache/tika:latest
    ports:
      - "9998:9998"
    restart: unless-stopped

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /qdrant_data:/qdrant/storage
    restart: unless-stopped
