FROM python:3.11-slim

WORKDIR /hayhooks

RUN apt-get update && apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY hayhooks/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY hayhooks /hayhooks

CMD ["hayhooks", "run"]
