FROM python:3.11-slim

WORKDIR /gradio

RUN apt-get update && apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY gradio/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY gradio /gradio

CMD ["python", "app.py"]